version: '3.8'

services:
  laravel:
    build:
      context: ./backend
    ports:
      - "8000:80"
    volumes:
         - ./backend/.env:/var/www/html/.env
         - ./backend/storage:/var/www/html/storage
    networks:
      - app-network
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - laravel

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:

volumes:
  dbdata:
